### ISSUE TITLE
Issue with Module Managr 2.6.25

### ISSUE THREAD

**Issue by sentania** [Sigma88/Sigma-PluronKhato#7]
[LOG 21:33:40.078] [ModuleManager] :AFTER[SIGMABINARY] pass
[LOG 21:33:40.089] [ModuleManager] Applying node Sigma/PluronKhato/Configs/Binary/PluronKhato_SigmaBinary/@Kopernicus:AFTER[SigmaBinary] to Kopernicus/Config/System/Kerbol System
[LOG 21:33:40.111] [ModuleManager] Cannot find key finalizeOrbit in Body
[LOG 21:33:40.112] [ModuleManager] Error - Cannot parse variable search when replacing (%) key finalizeOrbit = #$/Body:HAS[#SigmaBinary[Secondary]]/finalizeOrbit$
[LOG 21:33:40.115] [ModuleManager] Cannot find key finalizeOrbit in Body
[LOG 21:33:40.115] [ModuleManager] Error - Cannot parse variable search when replacing (%) key SigmaFinalize = #$/Body:HAS[#SigmaBinary[Secondary]]/finalizeOrbit$
[LOG 21:33:40.116] [ModuleManager] Cannot find key mass in Properties
[LOG 21:33:40.117] [ModuleManager] Error - Cannot parse variable search when editing key sphereOfInfluence = #$/Body:HAS[#SigmaBinary[Reference]]/Properties/mass$
[LOG 21:33:40.123] [ModuleManager] Error - Cannot parse variable search when editing key color = #$/Body:HAS[#SigmaBinary[Barycenter]]/Orbit/color$
[LOG 21:33:40.126] [ModuleManager] Error - Cannot parse variable search when editing key referenceBody = #$/Body:HAS[#SigmaBinary[Barycenter]]/name$
[LOG 21:33:40.147] [ModuleManager] Error - Cannot parse variable search when editing key sphereOfInfluence = #$/Body:HAS[#SigmaBinary[Barycenter]]/Properties/sphereOfInfluence$
[LOG 21:33:40.153] [ModuleManager] Applying node Sigma/PluronKhato/Configs/Binary/PluronKhato_SigmaBinary/@Contracts:AFTER[SigmaBinary] to Squad/Contracts/Contracts/Contracts
[LOG 21:33:40.159] [ModuleManager] Applying node Sigma/PluronKhato/Configs/Binary/PluronKhato_SigmaBinary/@Kopernicus:AFTER[SigmaBinary] to Kopernicus/Config/System/Kerbol System

**Comment by Sigma88** [comment]
this is not a module manager issue.
the mod has not been updated to 1.1.2 yet, what's probably throwing this error is the combination of this plus SigmaBinary.
I will release an update in the coming days

thanks for reporting

**Comment by Sigma88** [comment]
there
the latest release should solve your issue
let me know if the problem persists
